# BGKLV Large Map config

# Map topic, grid cell mininum resolution
topic: /occupied_cells_vis_array
resolution: 0.2
block_depth: 6 # Test-data octree depth (see Wang & Englot ICRA 2016)
max_range: 30 # Sensor max range (m)
original_size: true 

# Bounds on map height
min_z: -3.0
max_z: 3.0

# Kernel parameters
sf2: 0.1
ell: 0.6

# Sampling resolutions
free_resolution: 0.1
ds_resolution: 0.5  # Downsampling factor

# Free/Occupied Thresholds
free_thresh: 0.3
occupied_thresh: 0.7

# BGKL+ parameters
prior_A: 0.001 # Positive class (occupied)
prior_B: 0.001 # Negative class (unoccupied)
min_W: 0.01 #minimum unknown threshold
var_thresh: 0.001 # Threshold on variance to distinguish known/unknown

