# sim_structured config

# Information about range-finder data
scan_num: 12 # How many scans to use
max_range: 8 # Sensor max range (m)

# Bounds on map height
min_z: 0
max_z: 4.3

original_size: false
predict: false
